"""
Markdown report generation.
"""

import logging
from datetime import datetime
from typing import Dict, List

from ..core.models import Result, SearchConfig


logger = logging.getLogger(__name__)


def to_markdown_report(
    results_by_topic: Dict[str, List[Result]],
    config: SearchConfig,
    output_path: str
) -> None:
    """
    Generate a human-readable Markdown report.
    
    Args:
        results_by_topic: Dictionary mapping topic names to result lists
        config: SearchConfig object
        output_path: Path to save the Markdown file
    """
    logger.info(f"Generating Markdown report: {output_path}")
    
    with open(output_path, 'w', encoding='utf-8') as f:
        # Header
        f.write("# Research Report: Generative AI in Engineering\n\n")
        f.write(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        f.write(f"**Topics Searched:** {len(results_by_topic)}\n\n")
        
        f.write("---\n\n")
        
        # Results by topic
        for topic_name, results in results_by_topic.items():
            f.write(f"## {topic_name}\n\n")
            f.write(f"**Found {len(results)} relevant results**\n\n")
            
            for idx, result in enumerate(results, 1):
                f.write(f"### {idx}. {result.title}\n\n")
                
                # Metadata
                metadata_parts = []
                if result.published_date:
                    metadata_parts.append(f"📅 {result.published_date}")
                if result.domain:
                    metadata_parts.append(f"🌐 {result.domain}")
                if result.relevance_score > 0:
                    metadata_parts.append(f"⭐ Relevance: {result.relevance_score:.2f}")
                
                if metadata_parts:
                    f.write(" | ".join(metadata_parts) + "\n\n")
                
                # Link
                f.write(f"🔗 [View Article]({result.url})\n\n")
                
                # Summary
                summary = result.ai_summary if result.ai_summary else result.snippet[:200]
                f.write(f"**Summary:** {summary}\n\n")
                
                f.write("---\n\n")
        
        # Footer
        f.write("\n\n*Report generated by Research Automation Tool*\n")
    
    logger.info("Markdown report generated successfully")
